""
version: '3'
services:
  ml_app:
    build: .
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MLFLOW_EXPERIMENT_NAME=Iris_Experiment
    volumes:
      - .:/app
  mlflow_server:
    image: mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - mlflow_data:/mlflow
volumes:
  mlflow_data:
"""
